### ISSUE TITLE
Low-res favicons for HiDPI screens

### ISSUE THREAD

**Issue by legierski** [deanoemcke/thegreatsuspender#555]
When suspended on HiDPI screens (e.g. Ubuntu scaled to 200%), the favicons appear very pixelated, even if the original favicons were hi-res.
![screenshot from 2017-07-12 17-52-47](https://user-images.githubusercontent.com/1420343/28126821-ef6480d8-672a-11e7-9cd4-c1ad1fb0dadd.png)

**Comment by liamjohnston** [comment]
Looks like a duplicate of #541? That's been fixed, though I'm not sure if that fix has made it to the webstore yet (@deanoemcke?). Even if it has, automatic updates are off so you'r need to re-install the extension (back up your suspended tabs first!).

**Comment by legierski** [comment]
Oops, yes, it's a duplicate. Sorry.

That being said, I just updated to the latest version (6.30) and still see the same behaviour.

**Comment by liamjohnston** [comment]
@legierski 
Did you update on the chrome webstore? That's not been updated yet. And even when it is updated, automatic updates are (and always will be) disabled.

If you updated via the git repo, that's a bit weird and should have worked... can you confirm?

**Comment by liamjohnston** [comment]
Also, once you've established that you're running the correct version of the code, can you go here and tell me if it looks blurry/pixelated:

chrome://favicon/size/16@2x/https://stripe.com/gb
(yes I have committed the internet's favicons to memory)

**Comment by legierski** [comment]
@liamjohnston I've just tried to install it from github, but the browser complains about missing manifest.json file :(

**Comment by liamjohnston** [comment]
@legierski Did you follow the instructions for "Install as an extension from source" from here?
https://github.com/deanoemcke/thegreatsuspender

The main gotcha is step 4, make sure you select the _src directory_. Good luck...

I believe @deanoemcke plans to get the retina-friendly version onto the webstore soon-ish.

Also how does this look:
chrome://favicon/size/16@2x/https://stripe.com/gb
Pixelated or not?

**Comment by legierski** [comment]
@liamjohnston Oops, that's right, I misread the step 4.

That being said, I have now loaded the extension just fine, but the problem persist. Here's the screenshot of the extension loaded:

![screenshot from 2017-07-22 18-09-09](https://user-images.githubusercontent.com/1420343/28492750-34ac97e4-6f09-11e7-9d4c-eb25dadf0607.png)

And here's how the suspended tab favicon looks like next to active tab icon:

![screenshot from 2017-07-22 18-09-27](https://user-images.githubusercontent.com/1420343/28492757-4f0994ac-6f09-11e7-838c-6b315e5039f1.png)

The chrome://favicon/size/16@2x/https://stripe.com/gb seems to load just fine:

![screenshot from 2017-07-22 18-09-46](https://user-images.githubusercontent.com/1420343/28492758-591648dc-6f09-11e7-93ef-83c95c510c13.png)

**Comment by liamjohnston** [comment]
Hmm, that's a worry.

I guess just one more thing I want to check - that gmail tab, you suspended it _after_ installing the latest github version of TGS (and using that version - i.e. you don't still also have the webstore version installed)? 

Also, can you check one more for me please?:
chrome://favicon/size/16@2x/https://stackoverflow.com/
Note I'm interested in the favicon that appears in the tab's body, not the tab itself (as in your previous screenshot). I.e something like this:
![screen shot 2017-07-23 at 8 40 54 am](https://user-images.githubusercontent.com/1134713/28494439-c2ebf1a2-6f82-11e7-90f3-1941f5c153aa.png)

Thanks!

**Comment by legierski** [comment]
@liamjohnston That's correct, the only version of TGS that I have currently installed is the one from github, and yes, I did suspend the tab after installing it.

Here are the favicons:
![screenshot from 2017-07-22 22-57-02](https://user-images.githubusercontent.com/1420343/28494508-344b2770-6f31-11e7-9b71-4cb01cb9cc4f.png)
![screenshot from 2017-07-22 22-57-18](https://user-images.githubusercontent.com/1420343/28494511-38de85e8-6f31-11e7-9588-1285530833d4.png)
![screenshot from 2017-07-22 22-57-32](https://user-images.githubusercontent.com/1420343/28494512-3d7b289a-6f31-11e7-8e32-935d984cbdff.png)

**Comment by liamjohnston** [comment]
This is really weird. I've just checked master and it looks like there were a couple of changes that were missing (bad merge maybe?). I've just committed these to master - can you update your code and take another look? Not 100% sure this will fix your issue though, seeing as I couldn't replicate your issue with supposedly the same code.

Also, if your issue is still unresolved after updating, can you tell me how the favicon on a suspended tab body looks? I.e. the bit in the grey bar. This is how github master version looks like for me:
<img width="290" alt="screen shot 2017-07-23 at 11 33 40 am" src="https://user-images.githubusercontent.com/1134713/28495308-87e8c1ec-6f9c-11e7-88cb-2a8a6f2369b8.png">
vs how the webstore version currently looks:
<img width="308" alt="screen shot 2017-07-23 at 11 32 31 am" src="https://user-images.githubusercontent.com/1134713/28495310-9bc959a6-6f9c-11e7-8a6d-17dd9042179c.png">
(needs to be a website that actually serves a retina-friendly favion e.g. stackoverflow or codepen)

**Comment by legierski** [comment]
Success! Everything looks good now :) Thanks Liam.

![screenshot from 2017-07-23 02-14-48](https://user-images.githubusercontent.com/1420343/28495430-cfdf8a76-6f4c-11e7-9843-bd7a998e3814.png)
![screenshot from 2017-07-23 02-16-15](https://user-images.githubusercontent.com/1420343/28495436-ed4d785c-6f4c-11e7-9cae-dae69e68f5e4.png)
